# Generated by Django 5.1.1 on 2024-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_room_topic_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
