# Generated by Django 5.1.1 on 2024-10-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
